// Re-export everything from auth for backwards compatibility
export {
  generateToken,
  generateAccessToken,
  verifyAccessToken,
  generateRefreshToken,
  verifyRefreshToken,
  rotateRefreshToken,
  revokeAllUserTokens,
  revokeRefreshToken,
  generatePasswordResetToken,
  verifyPasswordResetToken,
  consumePasswordResetToken,
  getTokenFromHeader,
  authResponse,
  serverErrorResponse,
  successResponse,
  getAuthUser,
  requireAuth,
  createRoleGuard,
  auditLog,
  type AuthUser,
  type TokenPayload,
} from "./auth";
