import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { prisma } from "@/lib/db";
import { getAuthUser } from "@/lib/auth";

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const auth = await getAuthUser(request);
  if (!auth)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { id } = await params;
    const po = await prisma.purchaseOrder.findUnique({
      where: { id },
      include: {
        vendor: true,
        rfq: { select: { title: true, description: true, quantity: true } },
      },
    });

    if (!po)
      return NextResponse.json({ error: "PO not found" }, { status: 404 });

    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));

    doc.fontSize(20).text("PURCHASE ORDER", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`PO Number: ${po.poNumber}`);
    doc.text(`Date: ${new Date(po.createdAt).toLocaleDateString()}`);
    doc.moveDown();

    doc.fontSize(14).text("Vendor Details");
    doc.fontSize(12).text(`Name: ${po.vendor.name}`);
    doc.text(`Email: ${po.vendor.email}`);
    doc.moveDown();

    doc.fontSize(14).text("Order Details");
    doc.fontSize(12).text(`Item: ${po.rfq.title}`);
    doc.text(`Description: ${po.rfq.description}`);
    doc.text(`Quantity: ${po.rfq.quantity}`);
    doc.moveDown();

    doc.fontSize(14).text("Pricing");
    doc.fontSize(12).text(`Unit Price: Rs. ${po.totalAmount.toLocaleString()}`);
    doc.text(`Total Amount: Rs. ${po.totalAmount.toLocaleString()}`);
    doc.moveDown();

    doc.fontSize(10).text("Generated by ProcureFlow", { align: "center" });

    doc.end();

    return new Response(Buffer.concat(chunks), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${po.poNumber}.pdf"`,
      },
    });
  } catch (error) {
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}
